export const WIFI_CONFIG_REQUEST_HEADER = 1;
export const SUCCESS_RESPONSE_RESULT = 0;
export const WIFI_CONFIG_SUCCESS_RESPONSE_HEADER = 1;
export const INVALID_WIFI_CONFIG_RESPONSE_HEADER = 1;
export const WIFI_CONNECTION_FAILED_RESPONSE_HEADER = 2;

export const Definitions = {
  WIFI_CONFIG_REQUEST_HEADER,
  SUCCESS_RESPONSE_RESULT,
  WIFI_CONFIG_SUCCESS_RESPONSE_HEADER,
  INVALID_WIFI_CONFIG_RESPONSE_HEADER,
  WIFI_CONNECTION_FAILED_RESPONSE_HEADER
};
